gmail_draft_task:
  description: >
    Send an email to the client with the meeting minutes using the provided body: {body}
  expected_output: >
    To return whether the email was sent successfully or not
  agent: gmail_draft_agent
