retrieve_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    The list of 10 websites with the most relevant information about {topic}
  agent: retrieve_news

website_scrape_task:
  description: >
    Scrape the website for the latest news and information
  expected_output: >
    Fully scraped websites with all the important information from the website.
  agent: website_scraper

ai_news_write_task:
  description: >
    Create a professional news article about {topic} based on the research data provided.
    Write a comprehensive news article in markdown format covering the latest developments and trends.
    Focus on factual information, recent updates, and industry insights.
  expected_output: >
    A complete news article in markdown format with:
    - Clear headline
    - Introduction paragraph
    - Main content sections with relevant information
    - Conclusion
    Do not include code blocks or triple backticks.
  agent: ai_news_writer

file_write_task:
  description: >
    Save the completed news article to a markdown file in the news directory.
    Create a file with the current date and ensure all content from the previous task is preserved.
  expected_output: >
    Successfully created file: news/{date}_news_article.md
    The file contains the complete news article content from the previous task.
  agent: file_writer
